---
- name: installing and launching filebeat
  hosts: webservers
  become: yes
  tasks:

  - name: download filebeat deb
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.4.0-amd64.deb
 
  - name: install filebeat deb
    command: dpkg -i filebeat-7.4.0-amd64.deb

#  - name: Create directory
#    file:
#      path: /etc/ansible/filebeat/
#      state: directory
      #become: yes
      #become_user: root

  - name: drop in filebeat-config.yml 
    copy:
     src: /etc/ansible/filebeat-config.yml
     dest: /etc/filebeat/filebeat.yml
#     state: directory
 #    become: yes

  - name: enable and configure system module
    command: filebeat modules enable system

  - name: setup filebeat
    command: filebeat setup

  - name: start filebeat service
    command: service filebeat start

  - name: enable service filebeat on boot
    systemd:
      name: filebeat
      enabled: yes
